### ISSUE TITLE
App crashes when trying modify account if default transaction account no longer exist.

### ISSUE THREAD

**Issue by pingu8007** [codinguser/gnucash-android#654] opened 2017-02-16 01:14 UTC
#### Steps to reproduce the behaviour
1. Use double entry mode.
2. Create account A and B.
3. Set B's default transaction account to A.
4. Remove account A.
5. Modify account B, crash occurred.

#### Expected behaviour
Open account modifying interface.

#### Actual behaviour
App crashed.

#### Software specifications
* GnuCash Android version: 2.1.4
* System Android version: Nougat 7.1.1
* Device type: Google Pixel

**Comment by rivaldi8** [comment] 2017-02-26 19:22
Confirmed. Stack trace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.gnucash.android.devel/org.gnucash.android.ui.common.FormActivity}: java.lang.IllegalArgumentException: accounts with GUID 08b2c273aa3e96307fc6f4bbcc48563b does not exist in the db
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.access$900(ActivityThread.java:150)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: java.lang.IllegalArgumentException: accounts with GUID 08b2c273aa3e96307fc6f4bbcc48563b does not exist in the db
    at org.gnucash.android.db.adapter.DatabaseAdapter.getID(DatabaseAdapter.java:542)
    at org.gnucash.android.ui.account.AccountFormFragment.initializeViewsWithAccount(AccountFormFragment.java:395)
    at org.gnucash.android.ui.account.AccountFormFragment.onActivityCreated(AccountFormFragment.java:351)
    at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2089)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1133)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
    at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
    at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
    at android.app.Activity.performStart(Activity.java:6302)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
    at android.app.ActivityThread.access$900(ActivityThread.java:150) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by rivaldi8** [comment] 2017-03-23 20:20
@codinguser I've been looking at this issue and it seems it's solved by just uncommenting [this constraint](https://github.com/codinguser/gnucash-android/blob/a3927c8440c1d6471d3985567f101b5108939517/app/src/main/java/org/gnucash/android/db/DatabaseHelper.java#L80-L80) in the `accounts` table. Why did you leave it commented and implemented it in code (f10b4e433aa353cf0ef913f563be4025b5baa0ec) instead? Does it cause problems in other situations? In my tests I didn't find any issue.

**Comment by codinguser** [comment] 2017-03-24 13:05
@rivaldi8 I'm not exactly sure why I removed that constraint. 
But I recall that at some point, we removed constraints because they were taking a long time to process (via triggers) in the database. Therefore, we removed some and just made sure to perform the necessary operations directly via SQL. 
In this particular case, it might be okay to re-add it and modify the constraint to use "ON DELETE SET NULL"

But I have a question about this bug because I don't quite get why it exists (haven't looked deeper) 
Using the example the OP gave,, why does account B still have a reference to A after A has been deleted? 

I thought we [set A to NULL](https://github.com/codinguser/gnucash-android/blob/master/app/src/main/java/org/gnucash/android/db/adapter/AccountsDbAdapter.java#L1272) in all places where it is referenced after deletion?

**Comment by rivaldi8** [comment] 2017-03-24 17:08
Yes, I was confused at first too. The culprit is [DatabaseAdapter.deleteRecord(long rowId)](https://github.com/codinguser/gnucash-android/blob/77d9323bd5cb4a1fb40fb9a894943a9e9d7a73c4/app/src/main/java/org/gnucash/android/db/adapter/DatabaseAdapter.java#L516-L516) (not overriden by `AccountsDbAdapter`). The [unit test](https://github.com/codinguser/gnucash-android/blob/e5daf4bf0b3fc7ab2897a06b87fed8366b2db353/app/src/test/java/org/gnucash/android/test/unit/db/AccountsDbAdapterTest.java#L469-L469) checks [AccountsDbAdapter.deleteRecord(String uid)](https://github.com/codinguser/gnucash-android/blob/6849d6a608cb7b07b2a0ea43730e4fc1fa843b84/app/src/main/java/org/gnucash/android/db/adapter/AccountsDbAdapter.java#L1268-L1268) instead.

That's the nice thing about defining constraints in SQL. They are concise and you can't forget about them, they are always enforced.

**Comment by codinguser** [comment] 2017-03-25 21:57
I see... sneaky. :)
So I see 3 ways to go about this: 
* Override the method deleteRecord(long) in AccountsDbAdapter
* Change the call from the deleteRecord(long) to deleteRecord(String). 
* Both of the above (**preferred**)

Adding the foreign key constraint now will mean having to do a database migration, and since we cannot just alter tables in Sqlite, we have to drop the whole table, re-create it and then re-import it just in order to add that constraint. 
I would rather not put this effort now, especially as a few releases down the road, we will  be having a major db restructuring

**Comment by rivaldi8** [comment] 2017-03-26 15:18
Ok, I'll avoid adding the constraint for now.

**Comment by pingu8007** [comment] 2017-03-27 01:08
It seems we can prevent new invalid record created. But without DB restructuring, is it enough to solve invalid record that already exist?

**Comment by codinguser** [comment] 2017-03-27 13:40
@pingu8007 yes it would be possible for @rivaldi8 to add a migration which does not change the db schema, but just sets the values to NULL where the account with the ID no longer exists. 
Given the other changes in the code mentioned above, no further invalid records would be created

**Comment by rivaldi8** [comment] 2017-03-27 15:16
Yes, I'm working on it.

**Comment by rivaldi8** [comment] 2017-03-28 15:19
Fixed in develop.

**Closed by rivaldi8** 2017-03-28 15:19 UTC
Labels: bug
