### ISSUE TITLE
Export to Google Drive silently fails

### ISSUE THREAD

**Issue by bgainor** [codinguser/gnucash-android#616] opened 2016-11-15 17:26 UTC
Not sure if this is an issue related to 2.1.3, or if Google changed their API, but export to Google Drive seems to be silently failing.

#### Steps to reproduce the behaviour
1. Select "Export..." from left tray
2. Select export to "Google Drive", format QIF, default value for "Since"
3. Check "Delete transactions after export"
4. Tap "EXPORT"

#### Expected behaviour
Transactions to be deleted
Message "Exported to: Google Drive -> GnuCash"
QIF file to be in appropriate directory in Google Drive

#### Actual behaviour
Transactions are deleted (!)
Message "Exported to: Google Drive -> GnuCash"
No new file anywhere in Google Drive

#### Software specifications
* GnuCash Android version: 2.1.3
* System Android version: 6.0
* Device type: Moto X Pure Edition

**Comment by rivaldi8** [comment] 2016-11-19 11:35
I can't reproduce it.

Please, could you confirm that adding a transaction just before exporting, no file is created in Google Drive.

In some of my tests I couldn't see any folder or file listed. However, the .qif file appeared in the _Activity_ tab of the _Show details_ pane on the right. Could you check that no exported file appears there either (you may have to press the "i" button at the top right to show the pane).

**Comment by bgainor** [comment] 2016-11-21 14:42
Yes, I added a test transaction, and then exported. It said it was exporting to Google Drive, but no QIF files appear in the Activity tab in Google Drive.

**Comment by codinguser** [comment] 2016-11-21 20:52
@bgainor did you recently delete a GnuCash folder from Google Drive? Because the app uses folder IDs, sometimes, it happens that it keeps exporting to that folder even if it is in the trash. 
Alternatively you could try disconnecting and re-connecting Google Drive authorisation in the Export settings.

**Comment by bgainor** [comment] 2016-11-21 21:09
I don't remember deleting any folders (in fact, I had two different folders named GnuCash; I think as a result of switching to a new phone), but deauthorizing and reauthorizing Google Drive in the export settings seems to have done the trick (I now have _three_ folders named GnuCash). It still would be helpful, however, to not silently fail and still delete transactions when this happens, since in my case it seems to have been for no apparent reason, and resulted in data loss.

**Comment by codinguser** [comment] 2016-11-22 08:54
@bgainor Data loss sucks... sorry about that. 
Always remember that a backup is always generated immediately before deleting transactions. So you should be able to restore the state of your book before export. 

We are continuously working to improve our backup/export workflow.
Cheers,

**Comment by bgainor** [comment] 2016-11-22 13:09
Thanks, that's good to know. Sorry if I overreacted. I still think there should be a ticket for only deleting transactions if the export was successful, but should I close this one and open a new one specifically for that issue?

**Comment by rivaldi8** [comment] 2016-11-22 16:33
Don't close this one, it should be fixed too. I've filled another issue for the deletion of transactions: #618

**Comment by rivaldi8** [comment] 2016-11-22 19:41
@codinguser the code in [ExportAsyncTask.moveExportToGoogleDrive](https://github.com/rivaldi8/gnucash-android/blob/bed92fc20534dfd340308d2d3079ccdcbd3b1504/app/src/main/java/org/gnucash/android/export/ExportAsyncTask.java#L288) is run asynchronously, but the code that calls the method seems to expect it to run synchronously. I'd say the easiest way to fix these issues would be to make it synchronous. If you don't have any objection I can make the change.

**Comment by davidlandry93** [comment] 2016-12-03 17:31
I had the same problem a few days ago. 

Device Type: LG G3
Android Version: 6.0
GnuCash version: 2.1.3

**Comment by rivaldi8** [comment] 2016-12-08 20:31
I've looked into it again and finally decided to make it run synchronously. I've just made a minimum fix for 2.1.4. I'll try to improve the error reporting for exports in general for the next release.

Fixed in hotfix/patches (a082531).

**Closed by rivaldi8** 2016-12-08 20:31 UTC
