### ISSUE TITLE
Exception thrown when click "settings" menu , on android 4.3

### ISSUE THREAD

**Issue by lxbzmy** [codinguser/gnucash-android#440] opened 2015-11-28 09:42 UTC
Version : org.gnucash.android/2.0.3-beta0 Android; 4.3; 
```
No package identifier when getting value for resource number 0x00000000
FATAL EXCEPTION: main
 android.content.res.Resources$NotFoundException: Resource ID #0x0
 	at android.content.res.Resources.getValue(Resources.java:1119)
 	at android.content.res.Resources.getDrawable(Resources.java:694)
 	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
 	at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:177)
 	at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:170)
 	at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:53)
 	at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:74)

W/ActivityManager(  921):   Force finishing activity org.gnucash.android/.ui.settings.SettingsActivity
```

**Comment by rivaldi8** [comment] 2015-12-07 17:53
I'm not able to reproduce it. Is it still happening with 2.0.4? Does it happen every time or just sometimes? Is the application crashing or the exception just gets logged to Logcat?

**Comment by codinguser** [comment] 2016-08-18 07:38
Given no feedback, I will close this issue for now. 
@lxbzmy feel free to reopen it if you still experience it.

**Closed by codinguser** 2016-08-18 07:38 UTC
