### ISSUE TITLE
data lost when installing beta from google play

### ISSUE THREAD

**Issue by nikopp** [codinguser/gnucash-android#539] opened 2016-08-12 04:57 UTC
I switched to the beta in google play, got gnucash 2.1 and the transactions of the last week were gone.

That were exactly those transactions that I did not export so far.

Is this a problem of the beta system in google play or will this also happen when 2.1 is released?

**Comment by codinguser** [comment] 2016-08-12 16:08
No, no, that should *not* happen. 
Are all transactions gone, or just the ones from the last week?

**Comment by nikopp** [comment] 2016-08-12 17:14
Only the ones since the last export which I did last week.

Ngewi Fet <notifications@github.com> schrieb am Fr., 12. Aug. 2016, 18:08:

**Comment by codinguser** [comment] 2016-08-22 12:44
I haven't been able to reproduce this. 
@nikopp did you by any chance have scheduled exports?
One of the earlier bugs in beta1 was that scheduled actions were run too frequently, so maybe your data was exported and deleted without you realizing. 

@rivaldi8 Could you please investigate if there are some possibilities where the upgrade causes data loss? If recent transactions or something of the sort are affected.

**Comment by rivaldi8** [comment] 2016-08-22 15:34
Ok, I'll have a look.

**Comment by rivaldi8** [comment] 2016-08-22 17:28
@codinguser I haven't seen anything obvious in the upgrade code that might've caused this.

**Comment by codinguser** [comment] 2016-08-22 18:15
@rivaldi8 ok, thanks for looking into it

**Comment by codinguser** [comment] 2016-08-31 08:13
Cannot reproduce this, sorry @nikopp . I will close this issue for now. 
We will monitor it over the gradual rollout of v2.1.0 in the month of September.

**Closed by codinguser** 2016-08-31 08:13 UTC

**Comment by nikopp** [comment] 2016-09-10 23:29
@codinguser Sorry for not responding so far. No, I did not have scheduled exports.

I tried the beta again today and had no data loss.
