### ISSUE TITLE
Export notes with QIF

### ISSUE THREAD

**Issue by codinguser** [codinguser/gnucash-android#343] opened 2015-06-16 09:07 UTC

**Comment by hargi** [comment] 2015-07-19 06:03
Not exporting notes in QIF and/or XML currently is a no-go for me.
Would love to see that implemented.

**Comment by codinguser** [comment] 2016-08-10 14:07
@hargi notes are exported in XML. 
QIF is the tricky one

**Comment by rivaldi8** [comment] 2017-03-05 17:40
Which QIF field should be used?

**Comment by MisterY** [comment] 2017-05-29 14:05
Isn't M used for notes/description? And it is already utilised.

**Comment by rivaldi8** [comment] 2017-05-29 15:05
That's right. M is used for the description of transactions. We need another field for notes.

**Comment by MisterY** [comment] 2017-05-29 15:21
Ah, I see, you are using the terminology from GnuCash, which does not match QIF 100%.
Unfortunately, with QIF, description = notes. 
What is missing here is the Payee.

Which brings up an interesting point. I'm also very interested in adjusting the QIF export (starting with #690) and it might be useful to reshuffle the current field values. The description could be exported as the Payee (P) field, and the notes would go as the notes/description (M) field.

This would also solve my issues as I'm actually currently exporting to Quicken. Unfortunately, over the years, I was unable to transition to desktop GnuCash due to the lack of investment features but that's another story.

In any case, I'm happy to contribute to these changes (I'm also actively contributing to Money Manager Ex for Android) in QIF export & other features, if there's a concensus.

**Comment by codinguser** [comment] 2017-06-18 19:11
Thanks for the input @MisterY 
But isn't Payee `a person to whom money is paid or is to be paid, especially the person to whom a check is made payable`. 
Would that not represent a conflict if in the future the app actually supports a Payee?

**Comment by MisterY** [comment] 2017-06-18 20:14
Hi, @codinguser . While I can't comment on how the app will develop in the future and whether it will include additional fields, I am fairly certain that QIF will not include that field. So, here I was strictly speaking about QIF export and fields, and what to put in there. I, for example, am using Quicken and would like to import the transactions there.

Besides, I see no point in adding another field for the other party in a transaction when the amount already identifies in which direction the money flows.

**Comment by codinguser** [comment] 2017-06-18 21:03
@MisterY I see what you mean. 
So my question would be, does GnuCash desktop import the QIF description correctly when the description is set to the Payee field. If it works there, then we can implement it. Because our goal is to maximise compatibility with GnuCash desktop.

**Comment by MisterY** [comment] 2017-06-18 21:12
Yes, this is something to be confirmed. Having both Description and Notes fields makes Payee unnecessary. Either that or one of the other fields​ would be redundant.
I'll check tomorrow. If not, it would rather call for a bug report on the side of the desktop application, I believe.

**Comment by milankni** [comment] 2017-06-19 07:42
I use also OFX as intermediary (from CSV to OFX with the help of "ofxstatement" and eventually manual import to GnuCash) and AFAIK:
```
Payee (aka OFX.Name) becomes GnuCash.Description
Memo (OFX.Memo) becomes GnuCash.Notes
When Payee is empty, GnuCash imports Memo to "Description" and keeps "Notes" empty.
```
I would call it a bastardisation, too. Having separate Payee, Description and Note in GnuCash would be nice, but that's another story.

**Comment by MisterY** [comment] 2017-06-19 09:44
@milankni, thanks for the confirmation. 
While having both Description and Notes, in addition to Payee, would be handy, I believe that not all the fields are supported in QIF, unfortunately. Quicken also has a long memo field in addition to description and the payee, but I don't think that can be transferred via .qif file.
Still expecting some guidance as to how to move forward on this one. :)

**Comment by rivaldi8** [comment] 2017-06-19 15:48
I've just checked. GnuCash desktop imports correctly the Payee as the transaction description. If both Payee (P) and Memo (M) fields are set, it imports them as the _Description_ and _Notes_ respectively.

So we should just change to use Payee for the description and add the Memo field for notes.

**Comment by rivaldi8** [comment] 2017-07-07 17:13
Fixed in hotfix/patches.

**Closed by rivaldi8** 2017-07-07 17:13 UTC
Labels: enhancement
