### ISSUE TITLE
QIF export has no file extension

### ISSUE THREAD

**Issue by liamdennehy** [codinguser/gnucash-android#235] opened 2014-10-01 18:44 UTC
For Windows users, and apparently the desktop version of GnuCash, file extensions are key. The default file name for a QIF export is "GnuCash Android QIF Export", which GnuCash Desktop does not expect in it's default filename filter, so any import attempt starts with a blank folder. Setting an extension on an export does not carry over the next export.

This is a workflow blocker, especially for inexperienced Windows users where extensions sort out much complexity. Is there a negative impact to setting a suffix by default?

**Comment by MisterY** [comment] 2015-02-12 09:41
I'm exporting via Dropbox and don't see this issue. Could you try to export to SD Card or some other share service? That way could pinpoint where the issue originates.

**Comment by codinguser** [comment] 2015-06-19 10:53
Sorry, I cannot reproduce this issue. I will close it now.

**Closed by codinguser** 2015-06-19 10:53 UTC
